name: mp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - apptools=4.5.0=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - bleach=3.1.1=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.3.0=py_0
  - configobj=5.0.6=py_0
  - cryptography=2.8=py37h72c5cf5_1
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.11.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - envisage=4.9.2=py_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.2=h167e202_0
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - future=0.18.2=py37_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py37h6f030ca_1002
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.9.0=nompi_py37hcafd542_1103
  - h5utils=1.13.1=nompi_h8a2d148_1105
  - harminv=1.4.1=h8ce50c5_1004
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - importlib_metadata=1.5.0=py37_0
  - ipydatawidgets=4.0.1=py_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipyscales=0.4.0=py_1
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipyvolume=0.5.2=py37_0
  - ipywebrtc=0.5.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsoncpp=1.8.4=hc9558a2_1002
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=15_openblas
  - libcblas=3.8.0=15_openblas
  - libclang=9.0.1=default_hde54327_0
  - libctl=4.4.0=h516909a_0
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgdsii=0.21=hc9558a2_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libopenblas=0.3.8=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - markupsafe=1.1.1=py37h516909a_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h250f245_0
  - mayavi=4.7.1=py37h7eb8c7e_2
  - mistune=0.8.4=py37h516909a_1000
  - mpb=1.8.0=nompi_h6439e85_104
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - notebook=6.0.3=py37_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py37h95a1406_0
  - olefile=0.46=py_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h516909a_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.0.0=py37hefe7db6_0
  - pip=20.0.2=py_2
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py_2
  - pyface=6.1.2=py_0
  - pygments=2.5.2=py_0
  - pymeep=1.12.0=nompi_py37h5b05a10_108
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py37hcca6a23_1
  - pyrsistent=0.15.7=py37h516909a_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h357f687_2
  - python-dateutil=2.8.1=py_0
  - pythreejs=2.1.1=py_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - requests=2.23.0=py37_0
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scipy=1.4.1=py37h921218d_0
  - send2trash=1.5.0=py_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.30.1=hcee41ef_0
  - tbb=2019.9=hc9558a2_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_4
  - traitlets=4.3.3=py37_0
  - traits=6.0.0=py37h516909a_0
  - traitsui=6.1.3=py_0
  - traittypes=0.2.1=py_1
  - urllib3=1.25.7=py37_0
  - vtk=8.2.0=py37ha8e561a_202
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/ELE559/anaconda3/envs/mp

